apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: gitea-runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUNNER_URL
              value: "{{ .Values.runner.url }}"
            - name: RUNNER_TOKEN
              value: "{{ .Values.runner.token }}"
            - name: RUNNER_NAME
              value: "{{ .Values.runner.name }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
